# 📦 File: cloudbuild.yaml

steps:
  # 🛠️ Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/task-bot-service:$COMMIT_SHA', '.']

  # 🚚 Step 2: Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/task-bot-service:$COMMIT_SHA']

  # 🚀 Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'task-bot-service'              # 📛 Cloud Run service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/task-bot-service:$COMMIT_SHA'
      - '--region'
      - 'us-west1'                      # 🌍 Update if you're in a different region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'       # 🔐 x-api-key handles access — this is okay

# ⏳ Set a timeout for deployment (1 hour max)
timeout: 3600s
