# 📦 File: cloudbuild.yaml

steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/task-bot-service:$COMMIT_SHA', '.']

# Step 2: Push the Docker image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/task-bot-service:$COMMIT_SHA']

# Step 3: Deploy the image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'task-bot-service' # Name of your Cloud Run service
  - '--image'
  - 'gcr.io/$PROJECT_ID/task-bot-service:$COMMIT_SHA'
  - '--region'
  - 'us-west1' # IMPORTANT: Replace with your desired region (e.g., us-central1)
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated' # Adjust authentication as needed (for x-api-key)
  - '--set-env-vars'
  - 'CLOUD_RUN_SECRET_KEY=$$CLOUD_RUN_SECRET_KEY,TOGETHER_AI_API_KEY=$$TOGETHER_AI_API_KEY' # Referencing secrets

# This ensures the build waits for Cloud Run deployment to complete
timeout: 3600s # 1 hour timeout
